### ISSUE TITLE
Initial size of modal

### ISSUE THREAD

**Issue by sunqiang-leo** [DylanVann/ant-design-draggable-modal#8]
This component should allow user to set initial size (height, width) of the modal while still allow do re-size operation.. In current implementation, if height or width is set through props, then there is no way to do the resize operation.

**Comment by madalinul** [comment]
Also when setting width and height the drag functionality is limited to just a small area of the viewport.

**Comment by iversonwool** [comment]
When I set the modal width to 1200px, the modal box is not centered, only when I set 800px, the modal is centered.

**Comment by DylanVann** [comment]
I added `initialWidth` and `initialHeight` as props to the latest version (`0.0.16`).

As of now you probably shouldn't use `width` and `height`, maybe in the future in a controlled mode.
