### ISSUE TITLE
Typescript declaration for DraggableModalProps not supporting children

### ISSUE THREAD

**Issue by chrisbchrist** [DylanVann/ant-design-draggable-modal#9]
Hey, great library!  Tried to implement this in a TypeScript app, but the compiler throws errors when trying to pass child elements to the DraggableModal.  Took a look at the types and it looks like you're setting `DraggableModalProps` to the default AntD `ModalProps`, but they don't account for the children prop that's passed when the Modal has descendant elements.

I originally fixed this by extending `DraggableModalProps` to include children, but typing DraggableModal as a `FunctionComponent` is probably an easier solution as it will allow the component to inherit children automatically.

I've made a PR, but it's simple to correct.

**Comment by DylanVann** [comment]
Thanks for the PR!
